# -*- coding: utf-8 -*-
"""AI_LAB_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2AmUVinnPsYni3o8eOp8XFgc2bjWe5h
"""

import random

board=[" " for i in range(9)]
def display():
  print()
  print(board[0]+"|"+board[1]+"|"+board[2]+"")
  print("-+-+-")
  print(board[3]+"|"+board[4]+"|"+board[5]+"")
  print("-+-+-")
  print(board[6]+"|"+board[7]+"|"+board[8]+"")
  print()


def winner(symbol:str)->bool:
  if board[0]==board[1]==board[2]==symbol:
    return True
  elif board[3]==board[4]==board[5]==symbol:
    return True
  elif board[6]==board[7]==board[8]==symbol:
    return True

  elif board[0]==board[3]==board[6]==symbol:
    return True
  elif board[1]==board[4]==board[7]==symbol:
    return True
  elif board[2]==board[5]==board[8]==symbol:
    return True

  elif board[0]==board[4]==board[8]==symbol:
    return True
  elif board[2]==board[4]==board[6]==symbol:
    return True
  return False

def draw():
  return " " not in board

def play():
  print("TIC-TAC-TOE\n")
  display()
  print("\n\nX-You \nO-Computer")
  while True:
    ch=int(input("Enter your choice(1-9)")) - 1
    if ch<0 or ch>8:
      print("Invalid Move")
      continue
    if board[ch]!=" ":
      print("Invalid Move")
      continue
    board[ch]="X"

    if winner("X"):
      print("You Won!")
      display()
      break
    if draw():
      print("DRAW!!")
      display()
      break
    display()

    unused=[i for i in range(9) if board[i]==" "]
    ch=random.choice(unused)
    board[ch]="O"
    if winner("O"):
      print("Computer Won!")
      display()
      break
    if draw():
      print("DRAW!!")
      display()
      break
    display()


play()

room_a=input("ROOM_A enter clean/dirty (c/d)")
room_b=input("ROOM_B enter clean/dirty (c/d)")
# n=int(input("Enter number of rooms: "))
# rooms=[0]*n
# for i in range(n):
#   rooms[i]=input(f"ROOM_{i+1} enter clean/dirty (c/d)")
rooms=[room_a,room_b]
print("ROOMS:",rooms)

vacuum=int(input("Enter initial position of vacuum cleaner(1-a)(2-b)")) - 1

while "d" in rooms:
  if rooms[vacuum]=="d":
    print(f"ROOM: {'A' if vacuum == 0 else 'B'}, is dirty---CLEANING")
    rooms[vacuum]="c"
  else:
    print(f"ROOM: {'A' if vacuum == 0 else 'B'}, is already clean---GOING TO NEXT ROOM")


  vacuum=(vacuum+1)%len(rooms)

room_a = input("ROOM_A enter clean/dirty (c/d): ")
room_b = input("ROOM_B enter clean/dirty (c/d): ")
rooms = [room_a, room_b]
vacuum = int(input("Enter initial position of vacuum cleaner(1-A)(2-B): ")) - 1


for i in range(4):
    current_room_label = 'A' if vacuum == 0 else 'B'
    current_status = rooms[vacuum]

    print(f"\n[Step {i+1}] Vacuum is in Room {current_room_label}")


    if current_status == "d":
        print(f"Action: Perceived DIRTY -> CLEANING Room {current_room_label}")
        rooms[vacuum] = "c"
    else:
        print(f"Action: Perceived CLEAN -> MOVING to next room")
        vacuum = (vacuum + 1) % len(rooms)